defaults :
  - modulus_default
  - arch:
      - modified_fourier
  - optimizer : adam
  - scheduler : tf_exponential_lr
  - loss: sum
  - _self_

run_mode: 'train'

optimizer: 
  lr : 1e-3

scheduler:
  decay_rate: 0.99
  decay_steps: 2000

training:
  rec_results_freq : 10000
  rec_constraint_freq: 10000
  max_steps : 10000000

custom:
  parameterized: true
  exact_continuity: false
  quasirandom: true
